version: "3.9"

services:
  client-app:
    extends:
      file: client-app/docker-compose.yml
      service: web
    env_file: client-app/.env
  client-app-db:
    extends:
      file: client-app/docker-compose.yml
      service: client-app-db
    env_file: client-app/.env
  client-app-migration:
    extends:
      file: client-app/docker-compose.yml
      service: migration
    env_file: client-app/.env

  ticket-app:
    extends:
      file: ticket-app/docker-compose.yml
      service: ticket-service
    env_file: ticket-app/.env
  ticket-db:
    extends:
      file: ticket-app/docker-compose.yml
      service: ticket-db
    env_file: ticket-app/.env

  payment-app:
    extends:
      file: payment-app/docker-compose.yml
      service: payment-app
    env_file: payment-app/.env
  payment-app-db:
    extends:
      file: payment-app/docker-compose.yml
      service: payment-app
    env_file: payment-app/.env
