version: "3.9"

services:
  client-app:
    extends:
      file: client-app/docker-compose.yml
      service: client-app
    env_file: .env
  client-app-db:
    extends:
      file: client-app/docker-compose.yml
      service: client-app-db
    env_file: .env
  client-app-migration:
    extends:
      file: client-app/docker-compose.yml
      service: client-app-migration
    env_file: .env

  ticket-service:
    depends_on:
      - kafka
    extends:
      file: ticket-app/docker-compose.yml
      service: ticket-service
    env_file: .env
  ticket-db:
    extends:
      file: ticket-app/docker-compose.yml
      service: ticket-db
    env_file: .env

  payment-app:
    depends_on:
      - kafka
    extends:
      file: payment-app/docker-compose.yml
      service: payment-app
    env_file: .env

  payment-app-db:
    hostname: payment-app-db
    extends:
      file: payment-app/docker-compose.yml
      service: payment-app-db
    env_file: .env

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1