version: "3.7"

services:
  payment-app-db:
    hostname: payment-app-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: payment
    volumes:
      - ./db:/var/lib/postgresql/data/
  payment-app:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: >
      sh -c "
            npx prisma migrate dev &&
            npx prisma generate dev &&
            npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - payment-app-db
