version: "3.7"
networks:
  payment-app:
volumes:
  payment-app-data:
services:
  payment-app-db:
    hostname: payment-app-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: payment
    volumes:
      - payment-app-data:/data/db
    networks:
      - payment-app
  payment-app:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: >
      sh -c "
            npx prisma generate dev &&
            npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - payment-app-db
    networks:
      - payment-app
