services: 
  web: 
    build: . 
    image : django
    command: 
      python /code/django_app/manage.py runserver 0.0.0.0:8000 
    volumes: 
      - .:/code 
    ports: 
      - "8000:8000"
    depends_on: 
      - postgres_db 
      - migration

  migration:
    image: django
    command: 
      python /code/django_app/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - postgres_db

  postgres_db: 
    container_name: 
      postgres_client_pat
    image: 
      postgres:latest
    volumes: 
      - postgres_db:/var/lib/postgresql/data/ 
    env_file:
      - .env
    restart: 
      always
    ports: 
      - "5432:5432"

volumes:
  postgres_db:
    driver: local