services: 
  client-app: 
    build: . 
    image : django
    command: 
      python /code/django_app/manage.py runserver 0.0.0.0:8000 
    volumes: 
      - .:/code 
    ports: 
      - "8000:8000"
    depends_on: 
      - client-app-db 
      - client-app-migration

  client-app-migration:
    image: django
    command: 
      python /code/django_app/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - client-app-db

  client-app-db: 
    container_name: postgres_client_pat
    image: postgres:latest
    hostname: postgres_client_pat
    restart: on-failure
    environment:
      POSTGRES_USER: ${CLIENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CLIENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CLIENT_POSTGRES_DB}
    volumes: 
      - ./db:/var/lib/postgresql/data/
    env_file:
      - .env
    ports: 
      - "5432:5432"

volumes:
  postgres_db:
    driver: local