version: '3'

services:
  ticket-db:
    container_name: ticket-db
    image: postgres:16
    hostname: ticket-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${TICKET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TICKET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TICKET_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TICKET_POSTGRES_USER} -d ${TICKET_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/migration.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/postgresql/data/

  ticket-service:
    container_name: ticket-service
    build: .
    hostname: ticket-service
    ports:
      - "8002:6000"
    depends_on:
      ticket-db:
        condition: service_healthy
    environment:
      DB_USER: ${TICKET_POSTGRES_USER}
      DB_PASSWORD: ${TICKET_POSTGRES_PASSWORD}
      DB_NAME: ${TICKET_POSTGRES_DB}
      PORT: ${TICKET_PORT}
    volumes:
      - .:/app