# Generated by Django 4.2.7 on 2023-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(auto_created=True)),
                ('client_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('seat_number', models.IntegerField()),
                ('booking_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], max_length=255)),
            ],
            options={
                'unique_together': {('client_id', 'booking_id')},
            },
        ),
    ]
